[package]
name = "ziget"
version = "0.1.0"
edition = "2021"

[dependencies]

llvm-sys = { version = "180.0.0", features = ["prefer-static"] }
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
clap = { version = "4.3.4", features = ["derive"] }
